ps:
  shell: pwsh
  execution_policy: AllSigned
  timeout_sec: 180
  transcript_dir: logs/transcripts
  configuration_name: ''

app:
  host: 127.0.0.1
  port: 5050
  out_dir: out
  log_dir: logs

  require_windows_auth: false
  trusted_auth_header: X-Remote-User
